# Mark Shust's Magento 2 Docker Compose (https://github.com/markoshust/magento2-docker)
# Version 10.0.0

version: "3"

services:
  app:
    image: markoshust/magento2-nginx:1.13-0
    links:
      - db
      - phpfpm
    ports:
      - 8000:80

  phpfpm:
    image: markoshust/magento2-php:7.1-fpm-0
    links:
      - db

  db:
    image: percona:5.7
    ports:
      - 8001:3306
    env_file: docker/env/mysql.env

  setup:
    image: markoshust/magento2-php:7.1-fpm-0
    command: /usr/local/bin/mage-setup
    links:
      - db
    env_file: docker/env/setup.env
